config/routes.rb
Rails.application.routes.draw do
  root "people#index"

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all.order(:last_name)
  end

  def show
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to person_path(@person) # or redirect_to @person, this is the short version
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private
    def set_person
      # params = { ..., id: "1" }
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:first_name, :last_name, :avatar, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<div class="ui three item menu">
<%= link_to "People", people_path, class: "item" %>
<%= link_to "Add Person", new_person_path, class: "item" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <div class = "ui container">
      <%= yield %>
    </div>
    <%# Footer %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name", autofocus: true %>
  </div>

  <div class = "field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>

  <div class = "field">
    <%= f.label :avatar %>
    <%= f.text_field :avatar, required: true, placeholder: "Avatar" %>
  </div>

  <div class = "field">
    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder: "Phone Number" %>
  </div>

  <div class = "field">
    <%= f.label :email %>
    <%= f.text_field :email, required: true, placeholder: "Email" %>
  </div>

  <%= f.submit nil, class: "ui button green"%>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>

<%= render "form", person: @person %>

<%= link_to 'Show', person_path(@person) %>
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1 class="ui header">People</h1>
<%= link_to 'New Person', new_person_path, class:"ui button red" %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @people.each do |person| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://robohash.org/<%= person.avatar %>?set=set4" />
        </div>
        <div class="content">
          <%= link_to person.full_name, person, class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
              <%= link_to (edit_person_path(person)) do  %>
            <div class="ui basic green button">
            Edit
            </div>
            <%end%>
            <%= link_to(person_path(person), method: :delete, data: { confirm: "Are You Sure?"}) do%>
            <div class="ui basic red button">
              Delete 
            </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render "form", person: @person %>
<br />
<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="ui card">
  <div class="image">
    <img src="https://robohash.org/<%= @person.avatar %>?set=set4" />
  </div>
  <div class="content">
    <p class="header">
      <%= @person.first_name %> <%= @person.last_name %>
    </p>
    <div class="meta">
      <span class="date"><%= @person.phone %></span>
    </div>
    <div class="description">
      <%= @person.email %>
    </div>
  </div>
  <div class="extra content">
    <%= link_to 'Edit', edit_person_path(@person), class: "ui button blue" %> |
    <%= link_to 'Back', people_path, class: "ui button"%>
  </div>
</div>